### ISSUE TITLE
Couldn't find message for key main.contributes.commands.lcpr.simpleDebug.title.

### ISSUE THREAD

**Issue by ivaquero** [ccagml/leetcode-extension#190]
## 🐛 Bug Report(错误报告)

```console
[vscode-leetcode-problem-rating]: Couldn't find message for key main.contributes.commands.lcpr.simpleDebug.title.
```

## To Reproduce(重现)

```console
code --list-extensions
```

## Expected behavior(预期行为)

```console
vscode-leetcode-problem-rating
```

## Extension Output(扩展输出)

```console
[vscode-leetcode-problem-rating]: Couldn't find message for key main.contributes.commands.lcpr.simpleDebug.title.
```

## Your Environment

- *os(操作系统)*: macOS
- *extension settings(扩展设置)*: None
- *nodejs version(nodejs版本)*: 19.6.0
- *vscode version(vscode版本)*: 1.75
- *extension version(扩展版本)*: 2.15.1

**Comment by ccagml** [comment]
Fixed. Thanks!
