### ISSUE TITLE
增加周赛场次信息展示

### ISSUE THREAD

**Issue by JiaoZiLang** [ccagml/leetcode-extension#200]
## 建议
<img width="450" alt="image" src="https://user-images.githubusercontent.com/9896920/222322688-9340596c-3657-42b0-820c-3f283ac38773.png">
增加一个周赛场次与周赛第几题信息的一个展示。理论理解这些信息都可以从 data.json 中获取

**Comment by ccagml** [comment]
2.18.1加了
