### ISSUE TITLE
登录菜单没有LeetCode Account项

### ISSUE THREAD

**Issue by TangBoheng** [ccagml/leetcode-extension#203]
![Screenshot from 2023-03-08 17-00-20](https://user-images.githubusercontent.com/16973161/223669620-85bbf2f1-501b-45a6-8f54-6c2f29fd2e54.png)

**Comment by ccagml** [comment]
美区的登录使用了谷歌的[reCAPTCHA]验证机器人,导致没办法用代码请求登录,官方插件有讨论过这个问题(https://github.com/LeetCode-OpenSource/vscode-leetcode/issues/478)[https://github.com/LeetCode-OpenSource/vscode-leetcode/issues/478],看着讨论没什么办法,我就把美区的账号登录隐藏了

**Comment by TangBoheng** [comment]
@ccagml 
windows上用相同账号没有问题。这是ubuntu上的vscode，刚开始用的时候也没有这个问题，有办法完全把设定初始化吗？

**Comment by ccagml** [comment]
@TangBoheng  完全吧设定初始化 是指什么? 配置显示哪个选项吗
