### ISSUE TITLE
无法正常使用

### ISSUE THREAD

**Issue by zj970** [ccagml/leetcode-extension#212]
在最新版的VScode中使用该插件，出现一直登录的情况，并且卡在《正在切换登录点》

**Comment by zj970** [comment]
![图片](https://user-images.githubusercontent.com/80807367/230572787-3ea39ce7-c4cd-47fc-bcc9-adf4559a82f5.png)

**Comment by ccagml** [comment]
最新版版本号是多少?windows,linux,mac?

**Comment by zj970** [comment]
linux  vs 1.78.0-1680759472 amd64

**Comment by zj970** [comment]
zj970
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ccagml/leetcode-extension"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月7日(星期五) 下午4:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ccagml/leetcode-extension] 无法正常使用 (Issue #212)





 
最新版版本号是多少?windows,linux,mac?

**Comment by ccagml** [comment]
我这边试了没发现不能用的情况,不清楚你的环境有没有问题

**Comment by zj970** [comment]
![图片](https://user-images.githubusercontent.com/80807367/231031580-590d49a3-d918-4376-b0b3-eae643f38b71.png)
我的环境没安装特殊的东西，我后面试了一下另外一个Leetcode插件是可以用的

**Comment by zj970** [comment]
尝试过卸载并重新安装，安装后还是会出现图1的界面，并且点击插件中的任意按钮都无效

**Comment by zj970** [comment]
然后也做过一个尝试，就是直接在settings设置默认的登录点为cn，重启点击该插件还是出现最开始的图的问题，一直显示<正在切换登录点>

**Comment by ccagml** [comment]
你1.78.0是怎么下载的?
我只能从官网下载
1.77.1
b7886d7461186a5eac768481578c1d7ca80e2d21
x64

**Comment by zj970** [comment]
就配置了秘钥，然后使用apt更新....

**Comment by zj970** [comment]
ok.已解决，谢谢
