### ISSUE TITLE
看不到plus题库

### ISSUE THREAD

**Issue by PiuQiuPiaQia** [ccagml/leetcode-extension#222]
## 🐛 Bug Report(错误报告)
看不到plus题库
<img width="923" alt="image" src="https://github.com/ccagml/leetcode-extension/assets/43880841/360b5254-b81e-4795-9b91-f7302ab073a9">
<img width="434" alt="image" src="https://github.com/ccagml/leetcode-extension/assets/43880841/f3f0a7bf-22d4-4953-81f7-e1127e4a378a">

## To Reproduce(重现)

Steps to reproduce the behavior.(重现的步骤。)
a
## Expected behavior(预期行为)

A clear and concise description of what you expected to happen.(对您期望发生的事情进行清晰简洁的描述。)

## Extension Output(扩展输出)

Paste here the LeetCode extension log from output channel.(将输出通道中的 LeetCode 扩展日志粘贴到此处。)

Guidance: Press `Ctrl+Shift+U`, and toggle the channel to `LeetCode`.(按`Ctrl+Shift+U`，将频道切换到`LeetCode`。)

## Your Environment

- *os(操作系统)*:
- *extension settings(扩展设置)*:
- *nodejs version(nodejs版本)*:
- *vscode version(vscode版本)*:
- *extension version(扩展版本)*:

**Comment by ccagml** [comment]
那个精选分类的题目是我从官网看来的.我看不到plus题库对应的题目是哪些,

**Comment by PiuQiuPiaQia** [comment]
> 那个精选分类的题目是我从官网看来的.我看不到plus题库对应的题目是哪些,
比如这个，尊享面试100题，方便的话可以支持一下
https://leetcode.cn/studyplan/premium-algo-100/

**Comment by PiuQiuPiaQia** [comment]
> 那个精选分类的题目是我从官网看来的.我看不到plus题库对应的题目是哪些,

我能看到plus的题目，需要我帮你提供什么吗，接口返回值还是啥

**Comment by ccagml** [comment]
@PiuQiuPiaQia  那个精选分类的数据存放在https://github.com/ccagml/leetcode-extension/blob/main/src/dao/choiceDao.ts这个文件里, 有新的精选分类的话,你可以提交个pr

**Comment by PiuQiuPiaQia** [comment]
> @PiuQiuPiaQia 那个精选分类的数据存放在 https://github.com/ccagml/leetcode-extension/blob/main/src/dao/choiceDao.ts 这个文件里, 有新的精选分类的话,你可以提交个pr 内容应该简单,就name是显示名称,questions就是这个新的精选分类包含哪些题目

https://github.com/ccagml/leetcode-extension/pull/223   已提交

**Comment by ccagml** [comment]
@PiuQiuPiaQia v2.19.8,感谢
