### ISSUE TITLE
workspaceFolder 用的是绝对路径，对于有多个办公环境的场景不友好

### ISSUE THREAD

**Issue by M-Kepler** [ccagml/leetcode-extension#226]
## 🐛 Bug Report(错误报告)

A clear and concise description of what the bug is.(清晰简洁地描述错误是什么。)

workspaceFolder 必须是绝对路径，如果切换办公电脑后，该路径就失效了

## To Reproduce(重现)

Steps to reproduce the behavior.(重现的步骤。)

## Expected behavior(预期行为)

A clear and concise description of what you expected to happen.(对您期望发生的事情进行清晰简洁的描述。)

期望可以用变量，比如 workspaceFolder

## Extension Output(扩展输出)

Paste here the LeetCode extension log from output channel.(将输出通道中的 LeetCode 扩展日志粘贴到此处。)

Guidance: Press `Ctrl+Shift+U`, and toggle the channel to `LeetCode`.(按`Ctrl+Shift+U`，将频道切换到`LeetCode`。)

## Your Environment

- *os(操作系统)*: windows
- *extension settings(扩展设置)*:
- *nodejs version(nodejs版本)*:
- *vscode version(vscode版本)*:
- *extension version(扩展版本)*:

**Comment by ccagml** [comment]
不太理解,现在配置中的workspaceFolder不能配置吗

**Comment by ccagml** [comment]
跟vscodez中配置的级别有关系吗? 用户/远程/工作区

**Comment by M-Kepler** [comment]
`leetcode-problem-rating.workspaceFolder` 配置必须是电脑上的路径；不能用变量；

比如我在办公电脑路径是 `C:/Users/[用户名]/`
家里电脑的 [用户名] 是不同的，这样的话 `leetcode-problem-rating.workspaceFolder`  配置就起不到作用

不知道是否已有解决方法

**Comment by ccagml** [comment]
workspaceFolder 可以尝试从环境变量中读取数据 不太清楚是不是这样子,2.19.10

**Comment by M-Kepler** [comment]
好的，这样也可以解决，感谢解答👍
