### ISSUE TITLE
文件名是否支持英文文件名

### ISSUE THREAD

**Issue by tanggengsheng** [ccagml/leetcode-extension#234]
![image](https://github.com/ccagml/leetcode-extension/assets/138247852/8c7f4e19-79db-44dd-ab5d-5205ea98f9c7)
是不是可以增加一个选项，默认文件名可以选择英文（twosum）或者中文

**Comment by ccagml** [comment]
2.19.12更新了,之前取的有问题,filepath还是按这个文档的方式配置
https://github.com/LeetCode-OpenSource/vscode-leetcode/wiki/%E8%87%AA%E5%AE%9A%E4%B9%89%E9%A2%98%E7%9B%AE%E6%96%87%E4%BB%B6%E7%9A%84%E7%9B%B8%E5%AF%B9%E6%96%87%E4%BB%B6%E5%A4%B9%E8%B7%AF%E5%BE%84%E5%92%8C%E6%96%87%E4%BB%B6%E5%90%8D
