### ISSUE TITLE
希望可以支持再次执行上一次执行错误的用例

### ISSUE THREAD

**Issue by M-Kepler** [ccagml/leetcode-extension#236]
## 🐛 Bug Report(错误报告)

A clear and concise description of what the bug is.(清晰简洁地描述错误是什么。)

**希望可以支持再次执行上一次执行错误的用例**，比如有些题目提交错误是因为一些特殊的用例，比如非常长的输入；此时，希望可以有按钮除法上一次错误的用例，而不用手动输入，或者通过文件输入（通过文件输入好像有问题）

比如题目: https://leetcode.cn/submissions/detail/449970154/

labuladong 的 leetcode 插件已经支持，可以参考：https://labuladong.github.io/algo/intro/vscode/

## To Reproduce(重现)

Steps to reproduce the behavior.(重现的步骤。)
a
## Expected behavior(预期行为)

A clear and concise description of what you expected to happen.(对您期望发生的事情进行清晰简洁的描述。)

## Extension Output(扩展输出)

Paste here the LeetCode extension log from output channel.(将输出通道中的 LeetCode 扩展日志粘贴到此处。)

Guidance: Press `Ctrl+Shift+U`, and toggle the channel to `LeetCode`.(按`Ctrl+Shift+U`，将频道切换到`LeetCode`。)

## Your Environment

- *os(操作系统)*:
- *extension settings(扩展设置)*:
- *nodejs version(nodejs版本)*:
- *vscode version(vscode版本)*:
- *extension version(扩展版本)*:
-

**Comment by ccagml** [comment]
看起来这个项目没开源

**Comment by ccagml** [comment]
更新了 2.19.13
