### ISSUE TITLE
【错误报告】在 ID 含有空格的题目对应的文件中，点击 Description 按钮时，无法识别题目 ID

### ISSUE THREAD

**Issue by Kekwy** [ccagml/leetcode-extension#240]
## 🐛 Bug Report(错误报告)

在 ID 含有空格的题目对应的文件中，点击 Description 按钮时，无法识别题目 ID。

![图片](https://github.com/ccagml/leetcode-extension/assets/100838741/c7875832-930b-4413-916e-2a3df53313a4)

## To Reproduce(重现)

在 ID 含有空格的题目对应的文件中，点击 Description 按钮。

## Expected behavior(预期行为)

在左侧边栏展示题目描述。

## Extension Output(扩展输出)

`LeetCodeProblemRating` 通道没有输出，VScode右下角出现弹窗：

![图片](https://github.com/ccagml/leetcode-extension/assets/100838741/8aba7b67-c85a-4b20-b134-8b554698dcc8)

## Your Environment

- *os(操作系统)*: Win11
- *nodejs version(nodejs版本)*: 16.16.0
- *vscode version(vscode版本)*: 1.81.1
- *extension version(扩展版本)*: v2.19.13

**Comment by ccagml** [comment]
2.19.14 感谢
