### ISSUE TITLE
data.json获取数据报错是什么原因？

### ISSUE THREAD

**Issue by ManTang034** [ccagml/leetcode-extension#246]
从 https://zerotrac.github.io/leetcode_problem_rating/data.json 获取数据出错

**Comment by ccagml** [comment]
印象中获取失败了只是没有最新的分数数据,会使用不了吗?可能是没有代理访问不了github

**Comment by ccagml** [comment]
你可以试试你的浏览器能不能打开这个地址

**Comment by ManTang034** [comment]
挂了代理可以访问，但是还是显示获取数据出错

**Comment by ccagml** [comment]
是不是代理设置的有问题?
