### ISSUE TITLE
python3 debug报错

### ISSUE THREAD

**Issue by JasperMZP** [ccagml/leetcode-extension#247]
系统win10
sys.argv会忽略空字符串参数
![image](https://github.com/ccagml/leetcode-extension/assets/24272063/524ad65a-133c-47fa-ae5a-d0ec52d44864)
![image](https://github.com/ccagml/leetcode-extension/assets/24272063/541e7959-bc6e-4421-bcc3-304e159392ab)

**Comment by ccagml** [comment]
这是python包的问题吗?

**Comment by ccagml** [comment]
![image](https://github.com/ccagml/leetcode-extension/assets/16464096/0b817d27-878b-41d5-9b53-b0bba98646d8)
我试了一下,在4和5之间会有"",数组不会越界报错,你用的是什么python的调试器?是
Python
v2022.16.1
Microsoft
100,118,596
标识符
ms-python.python
这个吗

**Comment by ccagml** [comment]
2.19.19感谢,这样看起来win10不是一直用不了debug?
