### ISSUE TITLE
新建文件名为英文名

### ISSUE THREAD

**Issue by zj970** [ccagml/leetcode-extension#257]
## 🐛 Bug Report(错误报告)

A clear and concise description of what the bug is.(清晰简洁地描述错误是什么。)

## To Reproduce(重现)

Steps to reproduce the behavior.(重现的步骤。)
a
## Expected behavior(预期行为)

A clear and concise description of what you expected to happen.(对您期望发生的事情进行清晰简洁的描述。)

## Extension Output(扩展输出)

Paste here the LeetCode extension log from output channel.(将输出通道中的 LeetCode 扩展日志粘贴到此处。)

Guidance: Press `Ctrl+Shift+U`, and toggle the channel to `LeetCode`.(按`Ctrl+Shift+U`，将频道切换到`LeetCode`。)

## Your Environment

- *os(操作系统)*:
- *extension settings(扩展设置)*:
- *nodejs version(nodejs版本)*:
- *vscode version(vscode版本)*:
- *extension version(扩展版本)*:

**Comment by ccagml** [comment]
https://github.com/ccagml/leetcode-extension/issues/237#issuecomment-1727707659 是不是可以参考这个?

**Comment by zj970** [comment]
这个我已经尝试过，更改为name 和以及原来的kebab-case-name也不行，但是我日志提交里面cn_name,我尝试了一下，正常了，非常感谢
&nbsp;


zj970
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年10月30日(星期一) 上午9:22
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ccagml/leetcode-extension] 新建文件名为英文名 (Issue #257)





 
#237 (comment) 是不是可以参考这个?
