### ISSUE TITLE
Description not working

### ISSUE THREAD

**Issue by sgrtye** [ccagml/leetcode-extension#260]
## 🐛 Bug Report(错误报告)

在文件中，Description按键不能正确工作

## To Reproduce(重现)

1. 在Leetcode-problem-rating > Editor:Shortcuts中添加description
2. 在代码文件中点击Description按键
![20231030181104](https://github.com/ccagml/leetcode-extension/assets/55668018/9b09ccf0-698c-467d-92b2-2c701a920862)

## Expected behavior(预期行为)

打开一个额外的窗口显示Question description

## Extension Output(扩展输出)

无任何输出

## Your Environment

- *os(操作系统)*: Windows
- *extension settings(扩展设置)*: Latest
- *nodejs version(nodejs版本)*: Latest
- *vscode version(vscode版本)*: Latest
- *extension version(扩展版本)*: Latest

**Comment by ccagml** [comment]
我试了一下正常,你的是美区?

**Comment by sgrtye** [comment]
> 我试了一下正常,你的是美区?

在英国。 从extension里打开新的问题 然后选择code now能正常创建code的窗口和description的窗口 但是如果是已经打开的code窗口中点击description无法打开问题描述页面。 而且log里是空的

**Comment by sgrtye** [comment]
@ccagml 我在新的PR里修改了QuestionDataModule.ts中的getNodeByID方法。 在getfidMapQuestionData中，返回值应该是Map<string, TreeNodeModel>，但是在运行时key的类型是int。在我这里Windows和Mac上都不能使用Description Button，而且和proxy没有关系，因为返回的map是正确的，只是key的类型不对。

我在getNodeById里增加了分别处理key是string和int的逻辑，但是我没有找到为什么key会是int。麻烦测试后先发布新的版本吧 先把功能恢复了然后再研究怎么产生的bug。

**Comment by ccagml** [comment]
发布了3.1.5, 不应该是int, 我在debian11没弄出这个,所以一直不知道什么情况

**Comment by sgrtye** [comment]
@ccagml 按道理不同的操作系统不应该影响这个吧。 而且这个函数会在插件打开自动登陆之前跑一次 然后返回是的Map是空的 我就以为是proxy的问题 debug了好久发现真正的问题。 那我就先close这个了 然后有机会再去修复key的类型了
