### ISSUE TITLE
二叉树、链表相关题目咋 debug 呢

### ISSUE THREAD

**Issue by z-lunaticasylum** [ccagml/leetcode-extension#265]
就比如这道题，已经修改了入参的类型，但打断点调试还是报错
![image](https://github.com/ccagml/leetcode-extension/assets/72840446/51efaf70-eea5-4535-b865-4c4ea3b778d0)
![image](https://github.com/ccagml/leetcode-extension/assets/72840446/f4e62f21-c526-4b51-b1c7-2e1343147f38)

**Comment by ccagml** [comment]
3.1.6,感谢

**Comment by ccagml** [comment]
看着之前解析都需要测试用例的参数是[xx] 这样数组的形式,如果参数是其他形式,可能会使得TreeNode解析不出来

**Comment by z-lunaticasylum** [comment]
暂时还未发现有其他的哈，有的话我再提出，感谢
