### ISSUE TITLE
没有题目内容展示

### ISSUE THREAD

**Issue by JiaoZiLang** [ccagml/leetcode-extension#271]
很长一段时间（1-3week）打开插件没有拉出题目了。
效果：
![image](https://github.com/ccagml/leetcode-extension/assets/9896920/9475c13c-9e42-43b4-bdc4-8cdac72b6453)

终端提示：
![image](https://github.com/ccagml/leetcode-extension/assets/9896920/faf8c898-7acb-4256-ba50-92edc13d8f90)

尝试做法：
1. 退出 App，删除缓存，重新登录，没用；
2. 删除插件，重新安装，没用

**Comment by ccagml** [comment]
最近吗?是不是选了什么过滤题目的设置

**Comment by JiaoZiLang** [comment]
> 最近吗?是不是选了什么过滤题目的设置

没有设置过滤选项

**Comment by ccagml** [comment]
光这样没看出来是为什么,这几天我也有在用
windows上C:\Users\用户名\.lcpr\leetcode\cache\problems.json, 
linux上~/.lcpr/leetcode/cache/problems.json 是不是没有这个题目文件, 
是不是网络问题获取不到?
以前版本还能用吗?

**Comment by JiaoZiLang** [comment]
![image](https://github.com/ccagml/leetcode-extension/assets/9896920/2bbf4da5-97a0-47fd-aa58-94a3f16e79d7)
我都开始怀疑是我的设置问题，我尝试改一下设置看看

**Comment by JiaoZiLang** [comment]
{"useEndpointTranslation":true}%

**Comment by CTCSU** [comment]
我刚刚也遇到这个问题，一开始用Cookie 重新登录无法打开，再用账号密码登录就可以了。不清楚具体原因。
@JiaoZiLang

**Comment by JiaoZiLang** [comment]
> 我刚刚也遇到这个问题，一开始用Cookie 重新登录无法打开，再用账号密码登录就可以了。不清楚具体原因。 @JiaoZiLang
刚刚试了一下用账号密码登录，果真可以了，多谢多谢。
目前看情况，果真是 cookie 登录就有这个问题
