### ISSUE TITLE
Workspace folder 可以支持自定义多个路径么，

### ISSUE THREAD

**Issue by yrui-ql** [ccagml/leetcode-extension#274]
期望拓展下 Workspace folder 这个配置项， 支持配置多个路径。
为什么需要这么做呢？
我目前在使用的设备包含两台macos系统的设备和一个windows设备，在vscode上，而我的配置文件是同步的， 
这意味在在配置文件被同步后，配置里，a设备下生效的文件路径未必会命中b设备的文件路径，这很痛苦，每次切换设备想使用这个插件的话都得改这个路径。
所以有没有一种更加便捷的方法来处理这个问题？

我个人的想法是，或许可以加个文件路径列表， 在这个拓展开始运行的时候去扫描下这些路径，如果有效路径>=2，然后通过面板或者其他什么来告知当前生效的workspace路径有哪些，请选择一个作为工作目录

这样或许能解决这个问题 ？

**Comment by sgrtye** [comment]
![image](https://github.com/ccagml/leetcode-extension/assets/55668018/40db9b5c-be27-4a81-a72b-c3c2e80b030e)
进入插件设置
![image](https://github.com/ccagml/leetcode-extension/assets/55668018/2a8f708a-893c-4c0b-9ba8-1d3982524390)
 Workspace folder 取消勾选同步
这样每台设备就是单独配置了

**Comment by yrui-ql** [comment]
😓，确实，也是个方法，OK多谢



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年11月10日 11:47 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [ccagml/leetcode-extension] Workspace folder 可以支持自定义多个路径么， (Issue #274) |


进入插件设置

Workspace folder 取消勾选同步
这样每台设备就是单独配置了

**Comment by ccagml** [comment]
https://github.com/ccagml/leetcode-extension/issues/226 跟这个有关吗?一开始我也不清楚他要干嘛

**Comment by ccagml** [comment]
你的意思是,你的配置文件.vscode/settings.json 是同步的?
然后希望里面的leetcode-problem-rating.filePath 可以配置多个folder,filename的意思?

**Comment by yrui-ql** [comment]
两回事，单纯是不想因配置同步的关系在不同设备上重复反复设置工作目录，一个设备上设置一次就够了



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年11月10日 15:28 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [ccagml/leetcode-extension] Workspace folder 可以支持自定义多个路径么， (Issue #274) |

#226 跟这个有关吗?一开始我也不清楚他要干嘛

**Comment by ccagml** [comment]
那是什么?"leetcode-problem-rating.workspaceFolder" = ["path1", "path2", "path3"] 然后同步后看那个path能用吗?

**Comment by yrui-ql** [comment]
> 那是什么?"leetcode-problem-rating.workspaceFolder" = ["path1", "path2", "path3"] 然后同步后看那个path能用吗?

想法是这样，不过这个还是要看你打算如何设计啦，
因为这个issue的诉求始终是：
**不想因配置同步的关系在不同设备上反复设置工作目录**，但是这个拓展的其他配置其实是不受设备因素干扰的，所以，我当时就在想， 这个拓展有没有一个方案，来解决配置文件切换导致的工作目录失效的问题

当然， 建立这个issue只是想和作者做下探讨，探究下我这个想法的可行性

**Comment by ccagml** [comment]
3.1.10增加配置"leetcode-problem-rating.workspaceFolderList": ["路径1", "路径2"],
