### ISSUE TITLE
无分数题目的难度显示能否和题库保持一致

### ISSUE THREAD

**Issue by anthonyAndchen** [ccagml/leetcode-extension#276]
你好，插件非常好用，但是我想问问有些题目获取不到分数，所以不能显示出对应的难度，对于这些题目能不能按题库的难度来显示呀？可以在哪里设置吗？
![image](https://github.com/ccagml/leetcode-extension/assets/61610987/1d120908-403e-45f6-a129-74ed05adb395)

**Comment by ccagml** [comment]
题库的难度是指 原来的简单,中等,困难?

**Comment by anthonyAndchen** [comment]
> 题库的难度是指 原来的简单,中等,困难?

多谢回复！
嗯嗯是的，有分数的就按照分数来显示难度，没有分数的题目按照题目的的简单,中等,困难。

**Comment by ccagml** [comment]
3.1.10加了
