### ISSUE TITLE
多次点击debug不会结束之前的debug活动

### ISSUE THREAD

**Issue by h0zr** [ccagml/leetcode-extension#278]
当我点击测试用例的debug会开始debug

但如果我再次点击debug按钮

就会再开一个新的debug，而不是结束之前的debug活动

就会出现两个debug的黄框

![PixPin_2023-11-19_18-40-43](https://github.com/ccagml/leetcode-extension/assets/139520365/14e9eee8-d413-4834-a8d1-d3660b32308c)

**Comment by ccagml** [comment]
3.1.11 感谢
