### ISSUE TITLE
请问下早上开始点击submit之后没有反应，状态栏显示正在提交代码，就再没有反应了

### ISSUE THREAD

**Issue by miku1104** [ccagml/leetcode-extension#280]
![image](https://github.com/ccagml/leetcode-extension/assets/66500937/fcdcd374-4eb2-49f3-bfb4-bc086da840cb)
但是其他的功能比如调试什么的都正常，点击case测试样例的时候submission是空的
![image](https://github.com/ccagml/leetcode-extension/assets/66500937/03a3c10c-5d4c-439e-aed5-fc48944cec4f)

**Comment by shtshang** [comment]
出现一样的现象。我这边重登一下就好了，怀疑是不是cookie过期。但没有提示就很搞了。。。

**Comment by eeee0717** [comment]
重登有效
