### ISSUE TITLE
测试用例格式问题

### ISSUE THREAD

**Issue by eeee0717** [ccagml/leetcode-extension#281]
## 🐛 Bug Report(错误报告)

测试用例格式问题？测试用例中`\n8`后多`,`，去除`,`可以正常测试。
对比了T39.组合问题测试用例是没有`,`的，是否是获取leetcode原测试数据格式不同导致的？

## To Reproduce(重现)

T40.组合问题2点击allcase

## Extension Output(扩展输出)

![CleanShot 2023-12-15 at 10 26 29@2x](https://github.com/ccagml/leetcode-extension/assets/70054568/a8f5fab4-1f01-4b87-a1b3-8f8460e4a257)

## Your Environment

- _os(操作系统)_: macos

**Comment by ccagml** [comment]
看起来是因为40题leetcode原测试数据格式多了个,

**Comment by ccagml** [comment]
感谢3.1.12
