### ISSUE TITLE
题目信息获取失败

### ISSUE THREAD

**Issue by zhch-sun** [ccagml/leetcode-extension#286]
## 🐛 Bug Report(错误报告)
刷新题目时, 无法获取题目信息

## Extension Output(扩展输出)
{"code":101,"data":{}}
{}
{}
Error: tunneling socket could not be established, cause=connect EHOSTUNREACH 0.0.30.210:80 - Local (192.168.0.101:54887)

## Your Environment

- _os(操作系统)_:  13.6.1
- _nodejs version(nodejs 版本)_: 11.15
- _vscode version(vscode 版本)_: 1.85.1
- _extension version(扩展版本)_: 最新

**Comment by ccagml** [comment]
这个错误表明无法建立隧道连接，原因是主机不可达。具体而言，错误代码 EHOSTUNREACH 意味着主机不可达。

可能的原因和解决方法包括：

网络连接问题： 确保你的设备能够正常连接到网络。检查网络配置、防火墙设置等，确保没有阻止连接的问题。

目标主机不可达： 检查你正在尝试连接的目标主机（0.0.30.210）是否可用。可以尝试使用 ping 命令测试目标主机的可达性。

ping 0.0.30.210
如果无法 ping 通，可能是目标主机故障或不可达。

端口问题： 错误信息中显示端口 80，确保该端口没有被阻止。有时防火墙或路由器设置可能会阻止连接。

本地设备配置： 检查本地设备的网络配置，确保IP地址、子网掩码、网关等设置正确。

软件或服务问题： 如果你正在使用特定的软件或服务，可能存在其配置问题。检查相关的软件设置以确保一切正确。

如果以上方法都无法解决问题，可能需要更多的详细信息来进一步排除。

**Comment by Rilomilo** [comment]
@zhch-sun 你是否是在remote机器上使用的呢
