### ISSUE TITLE
tag of problem is spelled in error

### ISSUE THREAD

**Issue by ijpq** [ccagml/leetcode-extension#295]
## 🐛 Bug Report(错误报告)

this screenshot maybe strightforward enough.
![image](https://github.com/ccagml/leetcode-extension/assets/44460962/e8297464-e6be-465f-b936-42e14b561922)

## To Reproduce(重现)

log in leetcode.com, `tag`->`堆`, is it 栈 ?

## Your Environment

- _os(操作系统)_: omit
- _extension settings(扩展设置)_: by default
- _nodejs version(nodejs 版本)_: omit
- _vscode version(vscode 版本)_: 1.82.2
- _extension version(扩展版本)_: v3.1.16

**Comment by ccagml** [comment]
感谢,像图中的20题,官方给的tag是stack
翻译是谷歌批量翻译的
你是对的
