### ISSUE TITLE
case测试无法获取答案是否正确|增加判断显示

### ISSUE THREAD

**Issue by 578223592** [ccagml/leetcode-extension#300]
## 🐛 Bug Report(错误报告)

对于多答案的问题，现版本只能僵硬的比较字符串是否相同，而不是真正的判断答案是否正确。
期望能增加一个正误的显示。

## To Reproduce(重现)
题目：https://leetcode.cn/problems/generate-parentheses/
语言：cpp
code：
```

class Solution
{
public:
    vector<string> generateParenthesis(int n)
    {
        vector<vector<string>> dp(n + 1);
        dp[0] = vector<string>{""};
        dp[1] = vector<string>{"()"};
        for (int i = 2; i <= n; ++i)
        {
            for (int pNum = 0; pNum < i; ++pNum)
            {
                int qNum = i - pNum - 1;
                for (auto &itemp : dp[pNum]){
                    for(auto &itemq:dp[qNum]){
                        dp[i].emplace_back("("+itemp+")"+itemq);
                    }
                }
            }
        }
        return dp[n];
    }
};
```

## Expected behavior(预期行为)
如下，虽然结果不同，但是仍然是正确的。
![image](https://github.com/ccagml/leetcode-extension/assets/65906820/287392fb-18d1-45da-a9e4-5bd4d6d8aada)

目前显示看起来答案对比给人是错误的假象：

![image](https://github.com/ccagml/leetcode-extension/assets/65906820/bf0745c0-2a8b-41f8-a69c-fba851f70161)

## Your Environment

- _os(操作系统)_: windows11

**Comment by ccagml** [comment]
有什么思路吗? 这取决于有些题目并不要求答案顺序

**Comment by ccagml** [comment]
确实,3,1,18 感谢
