### ISSUE TITLE
可以自定义模板|或者增强现有模板

### ISSUE THREAD

**Issue by 578223592** [ccagml/leetcode-extension#307]
对于一些需要额外数据结构的题目，比如：二叉树的TreeNode定义、链表的ListNode等都需要手动取消注释。

建议对TreeNode、ListNode等直接写在模板里，因为LeetCode对这些内容的定义都是基本一样的。

或者支持自定义模板。

**Comment by ccagml** [comment]
你这个应该把你自己的模板写到vscode里面配置的includeTemplates就可以了吧,

**Comment by ccagml** [comment]
settings.json里面可以自己配置leetcode-problem-rating.includeTemplates

**Comment by 578223592** [comment]
@ccagml 感谢，使用还不是很熟练。后面试一试
