### ISSUE TITLE
最新版 case 提交答案错误上色好像失效了

### ISSUE THREAD

**Issue by 0xcaffebabe** [ccagml/leetcode-extension#309]
## 🐛 Bug Report(错误报告)

![image](https://github.com/ccagml/leetcode-extension/assets/34188127/a1011af0-a30a-4068-9baf-939c2c82c1f2)
![image](https://github.com/ccagml/leetcode-extension/assets/34188127/604f7ceb-4161-4bb9-963a-eb158f01cecb)
![image](https://github.com/ccagml/leetcode-extension/assets/34188127/a3a4be28-faf4-485e-8938-6d99ac7495c6)

## To Reproduce(重现)

Steps to reproduce the behavior.(重现的步骤。)

## Expected behavior(预期行为)

A clear and concise description of what you expected to happen.(对您期望发生的事情进行清晰简洁的描述。)

## Extension Output(扩展输出)

Paste here the LeetCode extension log from output channel.(将输出通道中的 LeetCode 扩展日志粘贴到此处。)

Guidance: Press `Ctrl+Shift+U`, and toggle the channel to `LeetCode`.(按`Ctrl+Shift+U`，将频道切换到`LeetCode`。)

## Your Environment

- _os(操作系统)_: win10
- _extension settings(扩展设置)_: 已开启错误答案上色
- _nodejs version(nodejs 版本)_:
- _vscode version(vscode 版本)_: 1.87.2
- _extension version(扩展版本)_:  最后更新 2024-03-11, 09:08:19

**Comment by ccagml** [comment]
3.1.20,感谢
