### ISSUE TITLE
submit和test不可用

### ISSUE THREAD

**Issue by Snow-Crash** [ccagml/leetcode-extension#311]
## 🐛 Bug Report(错误报告)

submit, test都不可用

## To Reproduce(重现)

使用cookie登录leetcode国际版，打开任意题目，点击submit，没有任何反应，vscode output显示[object Object]

或者点击test后输入测试用例，output显示 {"msg":"http error","statusCode":499}

测试过vscode的另外一个leetcode插件，submit正常

## Your Environment

- _os(操作系统)_: win11
- _extension settings(扩展设置)_: node path留空或者指向我安装的node，问题都一样。其他一切设置默认。
- _nodejs version(nodejs 版本)_: v20.11.1
- _vscode version(vscode 版本)_: 1.87.2
- _extension version(扩展版本)_: 3.1.20

**Comment by ccagml** [comment]
可以试试用新的登录国际站的方式,
选中复制最后一个 graphql 请求右键->复制-> 以 cURL(bash)格式复制
插件登录选择 使用 cURL Cookie 方式登录,输入账号,输入复制来的 cURL(bash)格式请求数据
