### ISSUE TITLE
能设置代理吗

### ISSUE THREAD

**Issue by yulunyue** [ccagml/leetcode-extension#316]
login: login: pass: pass: {"code":-2,"msg":{"errno":-4039,"code":"ETIMEDOUT","syscall":"connect","address":"212.64.63.124","port":443}}
{"code":-2,"msg":{"errno":-4039,"code":"ETIMEDOUT","syscall":"connect","address":"212.64.63.124","port":443}}

**Comment by ccagml** [comment]
正常很多系统软件都能接管网络请求走代理,不清楚为什么需要设置
