### ISSUE TITLE
搬砖工地 - 艾宾浩斯记忆法

### ISSUE THREAD

**Issue by YYCB** [ccagml/leetcode-extension#317]
Hi ， 搬砖工地的想法和之前背单词遇到的艾宾浩斯记忆法很相似；
可以参考艾宾浩斯记忆法，设计板砖工地的功能；
以1个月为维度，每天学习的内容，分别在1、2、4、7天进行重复。

**Comment by ccagml** [comment]
当时想法是参考艾宾浩斯记忆法的,
默认好像是14天,是可以手动设置几天后出现的, 
因为同一个题,对不同人的难度是不一样的,当时没想明白,应该怎么自动把一个题分配到第几天出现

**Comment by YYCB** [comment]
可以将当天所有AC的题,默认设置分别在第1天、第2天、第4天、第7天、第14天、第28天、第60天出现;
不需要在意题的难易程度,提供tag分类/Difficulty分类 筛选即可;
使用者可以自行选择重新做一遍or看之前AC的提交or跳过;
