### ISSUE TITLE
id大于3072的题目缺失

### ISSUE THREAD

**Issue by mole828** [ccagml/leetcode-extension#323]
## 🐛 Bug Report(错误报告)

插件获取到的全部题目中，id最大的为3072 。
2024年5月9日的国际版每日一题抽中了3075 。
截止2024年5月10日的国际版，对免费用户的最大题号为3139 。

## To Reproduce(重现)

尝试刷新题目列表，但并没有新的题目

## Expected behavior(预期行为)

更新题目

## Extension Output(扩展输出)

[日志](https://gist.github.com/mole828/f8c7987c9ea4336da76b3fa0174e0ed8)

## Your Environment

- _os(操作系统)_: macos 14.4.1 (23E224)
- _extension settings(扩展设置)_:
- _nodejs version(nodejs 版本)_:
- _vscode version(vscode 版本)_:
- _extension version(扩展版本)_: v3.2.1

**Comment by ccagml** [comment]
题目有个缓存,避免每次都拉取3000多题的信息,在登录、查找的最旁边的...里面有个删除题目缓存信息,删一下在重新登录应该就有新题目了

**Comment by mole828** [comment]
理解了，感谢解答
