### ISSUE TITLE
会员题没显示 Premium Problem not rendering

### ISSUE THREAD

**Issue by p59740** [ccagml/leetcode-extension#327]
## 🐛 Bug Report(错误报告)

leetcode.com 已开通会员, 但插件中未显示部分题目, 猜测是会员题的原因, 没有显示. 
请问会员题在插件中是支持的吗?

## To Reproduce(重现)

<img width="1016" alt="image" src="https://github.com/ccagml/leetcode-extension/assets/121592993/5924e8ae-af56-41b0-82d1-744355065c1f">

**Comment by ccagml** [comment]
有一个设置是 leetcode-problem-rating.showLocked
上锁的题目不显示, 我没用会员,不清楚这个有没有用

**Comment by p59740** [comment]
> 有一个设置是 leetcode-problem-rating.showLocked 上锁的题目不显示, 这个是官方插件的设置,我没有会员,不清楚这个有没有用

有用! 太棒了, 已解决, 感谢~!
