### ISSUE TITLE
无法debug，控制台显示Error:exit code "1"

### ISSUE THREAD

**Issue by Tsukishima1** [ccagml/leetcode-extension#330]
## 🐛 Bug Report(错误报告)

无法调试样例

## To Reproduce(重现)

点击样例下的`debug`

## Expected behavior(预期行为)

正常进入调试

## Extension Output(扩展输出)

g++: error: unrecognized command line option '-std=c++20'; did you mean '-std=c++2a'?
Error: exit code "1". 
    at ChildProcess.<anonymous> (c:\Users\xxx\\.vscode\extensions\ccagml.vscode-leetcode-problem-rating-3.2.3\out\src\utils\SystemUtils.js:221:35)
    at ChildProcess.emit (node:events:517:28)
    at ChildProcess.emit (node:domain:489:12)
    at maybeClose (node:internal/child_process:1098:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:303:5)

## Your Environment

- _os(操作系统)_: Windows11
- _extension settings(扩展设置)_:
- _nodejs version(nodejs 版本)_:20.11.0
- _vscode version(vscode 版本)_:1.89.1
- _extension version(扩展版本)_:3.2.3

**Comment by miku1104** [comment]
俺也一样，更新了一下g++之后就好了

**Comment by Tsukishima1** [comment]
> 俺也一样，更新了一下g++之后就好了

你肿么更新的 T.T

**Comment by miku1104** [comment]
> > 俺也一样，更新了一下g++之后就好了
> 
> 你肿么更新的 T.T

就是把编译器换了，下载能支持cpp20的g++然后把环境变量换了再把vscode里的编译器选一下新的就行，去mingw的github网页里下就行

**Comment by Tsukishima1** [comment]
> > > 俺也一样，更新了一下g++之后就好了
> > 
> > 
> > 你肿么更新的 T.T
> 
> 就是把编译器换了，下载能支持cpp20的g++然后把环境变量换了再把vscode里的编译器选一下新的就行，去mingw的github网页里下就行

可以了!!非常感谢!!o(*￣▽￣*)ブ

**Comment by Tsukishima1** [comment]
> > > 俺也一样，更新了一下g++之后就好了
> > 
> > 
> > 你肿么更新的 T.T
> 
> 就是把编译器换了，下载能支持cpp20的g++然后把环境变量换了再把vscode里的编译器选一下新的就行，去mingw的github网页里下就行

佬您好！再打扰您一下，我去官网https://www.mingw-w64.org/downloads/ 下载了w64devkit以后不会无法调试了、但是没办法直接查看STL库容器里的值，调试那里只有内存地址，请问您有没有出现这样的问题呀？还是我哪一步错了😭

**Comment by miku1104** [comment]
> > > > 俺也一样，更新了一下g++之后就好了
> > > 
> > > 
> > > 你肿么更新的 T.T
> > 
> > 
> > 就是把编译器换了，下载能支持cpp20的g++然后把环境变量换了再把vscode里的编译器选一下新的就行，去mingw的github网页里下就行
> 
> 佬您好！再打扰您一下，我去官网https://www.mingw-w64.org/downloads/ 下载了w64devkit以后不会无法调试了、但是没办法直接查看STL库容器里的值，调试那里只有内存地址，请问您有没有出现这样的问题呀？还是我哪一步错了😭

我也是有这个问题，查了一下是下的编译器没有pretty print的问题，但是没找到解决的办法，现在我是直接调试控制台里面手动查看容器变量sry

**Comment by Tsukishima1** [comment]
> > > > > 俺也一样，更新了一下g++之后就好了
> > > > 
> > > > 
> > > > 你肿么更新的 T.T
> > > 
> > > 
> > > 就是把编译器换了，下载能支持cpp20的g++然后把环境变量换了再把vscode里的编译器选一下新的就行，去mingw的github网页里下就行
> > 
> > 
> > 佬您好！再打扰您一下，我去官网https://www.mingw-w64.org/downloads/ 下载了w64devkit以后不会无法调试了、但是没办法直接查看STL库容器里的值，调试那里只有内存地址，请问您有没有出现这样的问题呀？还是我哪一步错了😭
> 
> 我也是有这个问题，查了一下是下的编译器没有pretty print的问题，但是没找到解决的办法，现在我是直接调试控制台里面手动查看容器变量sry

hey您好我发现是因为我g++版本（14.x）太高了可能还没有增加pretty print，我在https://github.com/niXman/mingw-builds-binaries/releases下载了13.2.0的版本重新配置了一下环境变量就可以了，给您参考一下，感谢回复！

**Comment by Tsukishima1** [comment]
> > > > > 俺也一样，更新了一下g++之后就好了
> > > > 
> > > > 
> > > > 你肿么更新的 T.T
> > > 
> > > 
> > > 就是把编译器换了，下载能支持cpp20的g++然后把环境变量换了再把vscode里的编译器选一下新的就行，去mingw的github网页里下就行
> > 
> > 
> > 佬您好！再打扰您一下，我去官网https://www.mingw-w64.org/downloads/ 下载了w64devkit以后不会无法调试了、但是没办法直接查看STL库容器里的值，调试那里只有内存地址，请问您有没有出现这样的问题呀？还是我哪一步错了😭
> 
> 我也是有这个问题，查了一下是下的编译器没有pretty print的问题，但是没找到解决的办法，现在我是直接调试控制台里面手动查看容器变量sry

hey您好我发现是因为我g++版本（14.x）太高了可能还没有增加pretty print，我在https://github.com/niXman/mingw-builds-binaries/releases 下载了13.2.0的版本重新配置了一下环境变量就可以了，给您参考一下，感谢回复！

**Comment by miku1104** [comment]
> > > > > > 俺也一样，更新了一下g++之后就好了
> > > > > 
> > > > > 
> > > > > 你肿么更新的 T.T
> > > > 
> > > > 
> > > > 就是把编译器换了，下载能支持cpp20的g++然后把环境变量换了再把vscode里的编译器选一下新的就行，去mingw的github网页里下就行
> > > 
> > > 
> > > 佬您好！再打扰您一下，我去官网https://www.mingw-w64.org/downloads/ 下载了w64devkit以后不会无法调试了、但是没办法直接查看STL库容器里的值，调试那里只有内存地址，请问您有没有出现这样的问题呀？还是我哪一步错了😭
> > 
> > 
> > 我也是有这个问题，查了一下是下的编译器没有pretty print的问题，但是没找到解决的办法，现在我是直接调试控制台里面手动查看容器变量sry
> 
> hey您好我发现是因为我g++版本（14.x）太高了可能还没有增加pretty print，我在https://github.com/niXman/mingw-builds-binaries/releases 下载了13.2.0的版本重新配置了一下环境变量就可以了，给您参考一下，感谢回复！

okok，谢谢啦，gdb调试起来确实太折磨了，感谢！
